# Generated by Django 4.0.2 on 2022-02-20 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_arrival'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Arrival',
        ),
    ]
