# Generated by Django 4.0.2 on 2022-02-23 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
