# Generated by Django 4.0.2 on 2022-03-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_orderitem_item_remove_orderitem_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='about_desc',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
