# Generated by Django 4.0.2 on 2022-03-13 12:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_about_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='about_desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
