# Generated by Django 4.0.2 on 2022-03-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='phone',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
