# Generated by Django 4.0 on 2021-12-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter_header', models.CharField(blank=True, max_length=100)),
                ('commenter_desc', models.CharField(blank=True, max_length=100)),
                ('commenter_fb_url', models.CharField(max_length=100)),
                ('commenter_twitter_url', models.CharField(max_length=100)),
                ('commenter_instagram_url', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
