# Generated by Django 4.0 on 2021-12-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_rename_commenter_desc_aboutteam_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutteam',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
